#!/usr/bin/env node

/**
 * Example: Submit a proof for census registration
 *
 * This script demonstrates how to submit a zero-knowledge proof
 * for census registration.
 *
 * Note: In a real application, the proof would be generated client-side
 * using the ZK circuits. This example uses mock data for demonstration.
 */

const API_URL = process.env.API_URL || 'http://localhost:3000';

async function submitProof(censusId) {
  console.log('🔐 Submitting proof for census registration...\n');

  // Mock proof data - in reality, this would be generated by the ZK circuit
  const proofData = {
    censusId: censusId || 'test-census-id',
    proof: {
      pi_a: [
        '12345678901234567890123456789012',
        '98765432109876543210987654321098',
      ],
      pi_b: [
        [
          '11111111111111111111111111111111',
          '22222222222222222222222222222222',
        ],
        [
          '33333333333333333333333333333333',
          '44444444444444444444444444444444',
        ],
      ],
      pi_c: [
        '55555555555555555555555555555555',
        '66666666666666666666666666666666',
      ],
      protocol: 'groth16',
      curve: 'bn128',
    },
    publicSignals: {
      nullifierHash: '0x' + generateRandomHash(),
      ageRange: 2, // 25-34 years old
      continent: 1, // Asia
      censusId: censusId || 'test-census-id',
      timestamp: Date.now(),
    },
    signature: 'mock-signature-' + Date.now(),
    publicKey: 'mock-pubkey-' + Date.now(),
  };

  try {
    const response = await fetch(`${API_URL}/api/v1/proof/submit`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(proofData),
    });

    const result = await response.json();

    if (response.ok) {
      console.log('✅ Proof submitted successfully!');
      console.log('\nTransaction Details:');
      console.log('  Signature:', result.data.transactionSignature);
      console.log('\nUpdated Statistics:');
      console.log('  Total Members:', result.data.stats.totalMembers);
      console.log('  Age Distribution:', result.data.stats.ageDistribution);
      console.log('  Location Distribution:', result.data.stats.continentDistribution);
    } else {
      console.error('❌ Failed to submit proof:', result.error);
    }
  } catch (error) {
    console.error('❌ Error:', error.message);
  }
}

function generateRandomHash() {
  return Array.from({ length: 64 }, () =>
    Math.floor(Math.random() * 16).toString(16)
  ).join('');
}

// Get census ID from command line argument
const censusId = process.argv[2];

if (!censusId) {
  console.log('Usage: node submit-proof.js <census-id>');
  console.log('Example: node submit-proof.js census-123456');
  process.exit(1);
}

submitProof(censusId);
